---
title: "Store Sales Project"
author: "Priyank Shroff"
date: "5/20/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(forecast)
library(ggplot2)
library(dplyr)
library(tidyr)
library(reshape2)
```

```{r}
filePath <- "/Users/priyankshroff/Desktop/UChiagoDocuments/Quarter3/30-TimeSeries/Project/data/store-sales-time-series-forecasting/"
train.Name <- "train.csv"
test.Name <- "test.csv"
stores.Name <- "stores.csv"
holidays.Name <- "holidays_events.csv"
transaction.Name <- "transactions.csv"

train.df <- read.csv(paste(filePath, train.Name, sep=""))
test.df <- read.csv(paste(filePath, test.Name, sep=""))
stores.df <- read.csv(paste(filePath, stores.Name, sep=""))
holidays.df <- read.csv(paste(filePath, holidays.Name, sep=""))
transaction.df <- read.csv(paste(filePath, transaction.Name, sep=""))

```

## Pre-Processing 
```{r}

group.by.func <- function(df) {
  df.group <- df %>% group_by(date, store_nbr, city, state) %>% summarise(
    sales = sum(sales),
    onpromotion = sum(onpromotion),
    transaction = sum(transactions)
  )
  
  return (df.group)
}

update_holidays <- function() {
  
  holidays.df <<- holidays.df[holidays.df$transferred=="False",]
  holidays.df.pivot <<- pivot_wider(holidays.df, names_from="locale", values_from="locale_name")
  
  holidays.df.local <<- holidays.df.pivot[!is.na(holidays.df.pivot$Local),c(1,5)]
  holidays.df.local$IsHoliday <<- rep(1, nrow(holidays.df.local))
  
  holidays.df.regional <<- holidays.df.pivot[!is.na(holidays.df.pivot$Regional),c(1,6)]
  holidays.df.regional$IsHoliday <<- rep(1, nrow(holidays.df.regional))
  
  holidays.df.national <<- holidays.df.pivot[!is.na(holidays.df.pivot$National),c(1,7)]
  holidays.df.national$IsHoliday <<- rep(1, nrow(holidays.df.national))
  
}


main <- function(df){

  df <- merge(x = df, y = stores.df, by.x = "store_nbr", by.y = "store_nbr")
  df <- merge(x = df, y = transaction.df, by.x = c("store_nbr", "date"), by.y = c("store_nbr", "date"))
  
  df.group <- group.by.func(df)
  
  df.group <- merge(x = df.group, y = holidays.df.local, by.x = c("date", "city"), by.y = c("date", "Local"), all.x = TRUE)
  df.group <- merge(x = df.group, y = holidays.df.regional, by.x = c("date", "state"), by.y = c("date", "Regional"), all.x = TRUE)
  df.group <- merge(x = df.group, y = holidays.df.national, by.x = c("date"), by.y = c("date"), all.x = TRUE)
  
  cols <- c("IsHoliday", "IsHoliday.x", "IsHoliday.y")
  df.group$Holiday <- apply(df.group[cols] == 1, 1, any)
  
  df.group <- df.group[,c(1,4,5,6,7,12)]
  
  return (df.group)
}

update_holidays()
df.group <- main(train.df)

```
## Step 2: EDA

```{r}
# number of stores: 54
length(unique(df.group$store_nbr))

# average sales across all stores: 12847.54
mean(df.group$sales)

# average number of promotions held across all stores: 93.73016
mean(df.group$onpromotion)

# average number of transactions across all stores: 55949.55
mean(df.group$transaction)
```

We will be only looking at the top 5 stores based on sales 

```{r}
group.by.sales <- df.group %>% group_by(store_nbr) %>% summarise(sales=sum(sales))
top.5.stores <- head(group.by.sales[order(group.by.sales$sales, decreasing = T),],5)$store_nbr

df.group <- filter(df.group, store_nbr %in% as.vector(top.5.stores))
```

```{r}

par(mfrow=c(5,1))

#df.group[df.group$store_nbr == as.vector(top.5.stores)[1],]

df.group$date <- as.Date(df.group$date)


ggplot(df.group[df.group$store_nbr == as.vector(top.5.stores)[1],], aes(x = date, y = sales, group=1)) +
  geom_line() + labs(title="Plot of Store 1")

ggplot(df.group[df.group$store_nbr == as.vector(top.5.stores)[2],], aes(x = date, y = sales, group=1)) +
  geom_line() + labs(title="Plot of Store 2")

ggplot(df.group[df.group$store_nbr == as.vector(top.5.stores)[3],], aes(x = date, y = sales, group=1)) +
  geom_line() + labs(title="Plot of Store 3")

ggplot(df.group[df.group$store_nbr == as.vector(top.5.stores)[4],], aes(x = date, y = sales, group=1)) +
  geom_line() + labs(title="Plot of Store 4")

ggplot(df.group[df.group$store_nbr == as.vector(top.5.stores)[5],], aes(x = date, y = sales, group=1)) +
  geom_line() + labs(title="Plot of Store 5")

```