---
title: "Time Series Analysis & Forecasting- Final Project"
author: "Adhiraj Maheshwari Srivastava"
date: "19/05/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Importing Libraries

```{r}
library(tseries)
library(forecast)
library(TSA)
library(fracdiff)
library(car)
library(dplyr)
library(xts)
library(zoo)
library(ggplot2)
```

## Reading the Data

For each of the datasets, we add a date column at the start
```{r}
train = read.csv('store-sales-time-series-forecasting/train.csv')
test = read.csv('store-sales-time-series-forecasting/test.csv')
transactions = read.csv('store-sales-time-series-forecasting/transactions.csv') 
stores = read.csv('store-sales-time-series-forecasting/stores.csv') 
oil = read.csv('store-sales-time-series-forecasting/oil.csv') 
holidays_events = read.csv('store-sales-time-series-forecasting/holidays_events.csv') 
sample_submission = read.csv('store-sales-time-series-forecasting/sample_submission.csv') 
```


Group By on Test
```{r}
train_grouped = train %>% group_by(date, store_nbr) %>%
                   summarise(sales = sum(sales),
                             onpromotion = sum(onpromotion),
                             .groups = 'drop')
 
View(train_grouped)
```

Joining the Datasets
```{r}
df = merge(train_grouped, stores, by="store_nbr")
```

```{r}
#df$unique= paste(df$store_nbr, df$date)
#transactions$unique= paste(transactions$store_nbr, transactions$date)
```


```{r}
df1=merge(df, transactions, by=c("store_nbr","date"))
```


```{r}
lapply(df1, function(x) {length((which(is.na(x))))})
summary(df1)
```


```{r}
store_grouped = df1 %>% group_by(store_nbr) %>%
                   summarise(sales = sum(sales),
                             transactions = sum(transactions),
                             .groups = 'drop')
 
View(store_grouped)
```

```{r}
store_grouped[order(-store_grouped$sales),]
store_grouped[order(-store_grouped$transactions),]
```

We take the top 5 stores in terms of sales

```{r}
df2 = filter(df1, df1$store_nbr == 44 |  df1$store_nbr == 45 |  df1$store_nbr == 47 |   df1$store_nbr == 3 |  df1$store_nbr == 49)
```

```{r}
df2$date=as.Date(df2$date)
```

```{r}
df2
#train_xt = as.xts(x = df2$sales, order.by = df2$date)

```

```{r}
plot_data_44= filter(df2, store_nbr==44)
plot_data_45= filter(df2, store_nbr==45)
plot_data_47= filter(df2, store_nbr==47)
plot_data_3= filter(df2, store_nbr==3)
plot_data_49= filter(df2, store_nbr==49)
```

```{r}
ggplot(data=plot_data_44, aes(x=date, y=sales, group=1)) +
  geom_line()+
  geom_point()

ggplot(data=plot_data_45, aes(x=date, y=sales, group=1)) +
  geom_line()+
  geom_point()

ggplot(data=plot_data_47, aes(x=date, y=sales, group=1)) +
  geom_line()+
  geom_point()

ggplot(data=plot_data_3, aes(x=date, y=sales, group=1)) +
  geom_line()+
  geom_point()

ggplot(data=plot_data_49, aes(x=date, y=sales, group=1)) +
  geom_line()+
  geom_point()
```


```{r}
#Setting up the legend for the graph
colors <- c("Store44" = "blue", "Store45" = "red", "Store47" = "green", "Store3" = "purple" , "Store49" = "black")

ggplot() + 
  geom_line(data=plot_data_44, aes(x=date, y=sales, color = "Store44")) + 
  geom_line(data=plot_data_45, aes(x=date, y=sales, color = "Store45")) +
  geom_line(data=plot_data_47, aes(x=date, y=sales, color = "Store47")) +
  geom_line(data=plot_data_3, aes(x=date, y=sales, color = "Store3")) +
  geom_line(data=plot_data_49, aes(x=date, y=sales, color = "Store49")) +
  labs(title="Sales for All Stores", x="Date", y="Sales", color="Legend")+scale_color_manual(values = colors)
```

```{r}
#Setting up the legend for the graph
colors <- c("Store44" = "blue", "Store45" = "red", "Store47" = "green", "Store3" = "purple" , "Store49" = "black")

#Making the graph (Blue for male, and red for female):
ggplot() + 
  geom_line(data=plot_data_44, aes(x=date, y=transactions, color = "Store44")) + 
  geom_line(data=plot_data_45, aes(x=date, y=transactions, color = "Store45")) +
  geom_line(data=plot_data_47, aes(x=date, y=transactions, color = "Store47")) +
  geom_line(data=plot_data_3, aes(x=date, y=transactions, color = "Store3")) +
  geom_line(data=plot_data_49, aes(x=date, y=transactions, color = "Store49")) +
  labs(title"Transactions for All Stores", x="Date", y="Transactions", color="Legend")+scale_color_manual(values = colors)
```

